language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "gpR+1g9rUf9GoZkEkAKGROzze8D+JPS08QppUCcFbi4Dooobhkd2slA64NoPc88I00LpLDLliaxg/Gle+dEQKhAQd+wQ3Pow5pubwgUWDriH27YbcVyXoeglPynFakRD0limAGfUBALXN0NmltmlVE8WmZE7INaNHvPxaDdjTBmEqNiX80bHxE7IQcXTt/JNwepKnNdtU5H7IzENvBKvaSkpZKVbW5vcGts+GFJLmVmsBdksWwlpkLpfr3TZKWRYSIqkkIIoGSGU0ngyijnX0AWAjTv6qOxXLz/Lw0TW9TDvvISEYaqCp/Nvs6EY9l/sk8OkVL1BwYu7PnGSoxa46CTwDGyLI7RhfruPqBkQ/DcGXeviC2JClUzxcMv/vlJ4Bg2g9aDy+gWizf8AAyIGRUbKbahje7d15PzU7OCRp+JyYOpjPUle+UrMxZGt4ku01W9HI2ac8kgwzDITqUP8Bk6jXt0WeRgtjmI5GH4GjrKTKjNEX3oL/yzpG8+jHhNCTfvYvWbxEj/1t+g7AHyJJ5/xzD4Cxz0Oa+UeQFvD95V+o+q6dwVnAlfjxhregA33ZRWNQRPwm75Osb6zoKnMoxaqvcc5ORnokyuRGzqEMiwKgNSkR79tYxqPYHJUO4Q3OqoJ+HMxooT5qaxwEQhGC3C0NuPWGJXzR9zirIoCh5E="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
